### ISSUE TITLE
2.3.1 instant crash

### ISSUE THREAD

**Issue by drodmantras** [thebarbican19/BatteryBoi#42]
2.3.1 instalntly crashes after opening.

**Comment by thebarbican19** [comment]
What is the OS Version?

**Comment by asboy-gh** [comment]
I’m getting this problem too (macOS 13.5.2). I hope you can find the problem because I loved using batteryboi 😢  From: Joe Barbour ***@***.***>Reply: thebarbican19/BatteryBoi ***@***.***>Date: September 17, 2023 at 11:04:10 PMTo: thebarbican19/BatteryBoi ***@***.***>CC: Subscribed ***@***.***>Subject:  Re: [thebarbican19/BatteryBoi] 2.3.1 instant crash (Issue #42)  
What is the OS Version?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/thebarbican19/BatteryBoi/issues/42#issuecomment-1722568495",
"url": "https://github.com/thebarbican19/BatteryBoi/issues/42#issuecomment-1722568495",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thebarbican19** [comment]
@drodmantras & @asboy-gh, I think I have identified the issue and just pushed a fix. However as I cannot replicate myself, I am gonna need help testing this.

**Comment by rabbly** [comment]
I'm having an instance crash on the new version just released a few minutes ago.  macOS 13.5.2 (22G91)

**Comment by thebarbican19** [comment]
@rabbly, Yeah I know, I broke it for everyone it seems by foolishly not commenting out some untested code. I have just pushed a new version that addresses it.

**Comment by rabbly** [comment]
Oops! All good now :)

Hopefully this version fixes some issues I was having where clicking the menu bar icon wouldn't bring up the app. I'll let you know if I encounter that still with a new issue.

**Comment by thebarbican19** [comment]
Phew! Thanks for letting me know. The animation is still buggy so it may not be resolved but hopefully I can find some time this week.

**Comment by drodmantras** [comment]
Sadly not fixed for me 

https://github.com/thebarbican19/BatteryBoi/assets/58110607/840f2e1b-ea30-4e39-8745-b7c6f7c2185e
